### ISSUE TITLE
Time data does not match format

### ISSUE THREAD

**Issue by TheSuperBeaver** [mawinkler/pyastroweatherio#4]
Hi Markus !

I have a bug with one of the latest versions of astroweather and pyastroweatherio 

in the homeassistant log i receive this error multiple times : 

`2024-10-16 16:40:25.173 ERROR (MainThread) [custom_components.astroweather] Unexpected error fetching astroweather data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 370, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyastroweatherio/client.py", line 138, in get_location_data
    return await self._get_location_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyastroweatherio/client.py", line 371, in _get_location_data
    "uptonight_comets": await self._get_comets(),
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyastroweatherio/client.py", line 949, in _get_comets
    datetime.strptime(rise_time_local, "%m/%d/%Y %H:%M:%S")
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-10-15 07:07:08' does not match format '%m/%d/%Y %H:%M:%S'
`

Is it maybe a version that I should have upgraded but forgot ?

**Comment by mawinkler** [comment]
Hi,
which versions are you using of hass, astroweather and pyastroweatherio?

**Comment by TheSuperBeaver** [comment]
The error appears when I'm on hass : 2024.11.0.dev202410140231
with astroweather : 0.61.1
and pyastroweatherio : 0.61.1 (I believe, i didn't upgraded this one, not sure that i need to since it's a dependency)

**Comment by mawinkler** [comment]
closing
